### ISSUE TITLE
Deprecated: Use of "self" in callables

### ISSUE THREAD

**Issue by kylehqcom** [logtail/monolog-logtail#19]
As error in the better stack logs when running version PHP 8.2.7

Deprecated: Use of "self" in callables is deprecated in vendor/logtail/monolog-logtail/src/Monolog/LogtailFormatter.php on line 30

Refer: https://github.com/logtail/monolog-logtail/blob/master/src/Monolog/LogtailFormatter.php#L35

**Comment by PetrHeinz** [comment]
Hello @kylehqcom and thank you for reporting this 🙌 

I can see the deprecated call has been fixed in and [`v3.0.0`](https://github.com/logtail/monolog-logtail/compare/v2.0.0...v3.0.0#diff-a6dec5104d805bfbcf4a25070b199f281c0af7563b45a5e71598bece35cf1707L30-R35) and [`v2.0.1`](https://github.com/logtail/monolog-logtail/compare/v2.0.0...v2.0.1#diff-a6dec5104d805bfbcf4a25070b199f281c0af7563b45a5e71598bece35cf1707L30-R30).

Can you please make sure you're using the latest version of the package? 🙏

I wasn't able to reproduce the issue in either 3.x nor 2.x versions.
